builds:
- main: .
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  gitea:
    owner: tdemin
    name: syg_go

gitea_urls:
  api: https://git.tdem.in/api/v1/
